[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "alloc", "compiler_builtins"]

[build]
target = "i686-unknown-none-elf.json"
rustflags = [
	"-C",
	"force-frame-pointers=y",
	"-C",
	"symbol-mangling-version=v0",
	"-C",
	"panic=abort",
	"-C",
	"relocation-model=static",
	'--cfg',
	'log_level="debug"',          # ALL = debug > info > warn > error
	# '--cfg',
	# 'trace_feature="oom"',
	# '--cfg',
	# 'trace_feature="inode_iter"',
	# '--cfg',
	# 'trace_feature="sb-read-inode"',
	# '--cfg',
	# 'trace_feature="ext2-idspace"',
	# '--cfg',
	# 'trace_feature="block_pool"',
	# '--cfg', 'trace_feature="lru"',
	# '--cfg', 'trace_feature="ext2-mount"',
	# '--cfg',
	# 'trace_feature="ext2-unmount"',
]
