[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "alloc", "compiler_builtins"]

[build]
target = "i686-unknown-none-elf.json"
rustflags = [
	"-C",
	"force-frame-pointers=y",
	"-C",
	"symbol-mangling-version=v0",
	"-C",
	"panic=abort",
	"-C",
	"relocation-model=static",
	'--cfg',
	'log_level="debug"',            # ALL = debug > info > warn > error
	'--cfg',
	'trace_feature="ext2-idspace"',
	'--cfg',
	'trace_feature="ext2-truncate"',
	'--cfg',
	'trace_feature="time-truncate"',
]
