[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "alloc", "compiler_builtins"]

[build]
target = "i686-unknown-none-elf.json"
rustflags = [
	"-C",
	"force-frame-pointers=y",
	"-C",
	"symbol-mangling-version=v0",
	"-C",
	"panic=abort",
	"-C",
	"relocation-model=static",
	'--cfg',
	'log_level="debug"',            # ALL = debug > info > warn > error
	# '--cfg',
	# 'trace_feature="time-dma-verbose"',
	'--cfg',
	'trace_feature="syscall"',
	# '--cfg',
	# 'trace_feature="sleep_atomic"',
	# '--cfg',
	# 'trace_feature="block_pool"',
	# '--cfg',
	# 'trace_feature="partition-load_async"',
	# '--cfg',
	# 'trace_feature="ext2-read_inode"',
	'--cfg',
	'trace_feature="ext2-symlink"',
]
