[package]
name = "timestamp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]
test = false
bench = false

[dependencies]
kfs = { path = ".." }
kfs_macro = { path = "../kfs_macro" }